# Generated by Django 3.1.4 on 2021-03-20 18:55

import api.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=api.models.Pizza.get_next_number, unique=True, verbose_name='Poradové číslo')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizze',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'Veľkosť',
                'verbose_name_plural': 'Veľkosti',
            },
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('weight', models.IntegerField(verbose_name='Hmotnosť')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size', to='api.size', verbose_name='Veľkosť')),
                ('pizza', modelcluster.fields.ParentalKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='size_values', to='api.pizza')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
