# Generated by Django 3.1.4 on 2021-03-20 19:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=api.models.Allergen.get_next_number, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_extra', models.DecimalField(decimal_places=2, max_digits=4)),
                ('allergens', models.ManyToManyField(related_name='ingredients', to='api.Allergen')),
            ],
            options={
                'verbose_name': 'Surovina',
                'verbose_name_plural': 'Suroviny',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='pizzas', to='api.Ingredient'),
        ),
    ]
